# Planet Configuration

title = "Palikkalinkit"

[[feeds]]
type = "atom"
url = "https://cyclopicbricks.blogspot.com/feeds/posts/default"

[[feeds]]
type = "rss"
url = "https://hovinet.com/?feed=rss2"

[[feeds]]
type = "youtube"
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UC1gpjceZQv8qKxcCJB4BKhw"

[[feeds]]
type = "youtube"
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCIobvkZGI5zAd55vooUokqg"

[[feeds]]
type = "youtube"
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCWNl-SeihlkLKGsx9L9450Q"

[[feeds]]
type = "youtube"
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCRM3pjKaP5BoevfZuE9_kEw"

[[feeds]]
type = "youtube"
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UC3doy6NwIkzNMMBba3xOOJw"

[[feeds]]
type = "flickr"
url = "https://www.flickr.com/services/feeds/photos_public.gne?id=63411232@N00&lang=en-us&format=atom"

[[feeds]]
type = "kuvatfi"
title = "Palikkatakomo"
url = "https://palikkatakomo.kuvat.fi/kuvat/rss/"

[[feeds]]
# Kristallikuningas
type = "youtube"
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UC2oUI4QDXFBJ6kHorUvV4TA"

[[feeds]]
# BrickDevil
type = "youtube"
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCevQ7uLnqJYWeTDLtc8I4uw"

[[feeds]]
# Vilzu
type = "youtube"
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCIDvVMnuu8WAeIXA_GsnNwA"
