# Planet Configuration

title = "Palikkaverse"

[[feeds]]
type = "blog"
title = "Cyclopic Bricks"
url = "https://cyclopicbricks.blogspot.com/feeds/posts/default?alt=rss"

[[feeds]]
type = "youtube"
title = "FinnBrixStudio"
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UC1gpjceZQv8qKxcCJB4BKhw"
