# Planet Configuration

title = "My Haskell Planet"

[[feeds]]
type = "blog"
title = "Haskell Weekly"
url = "https://haskellweekly.news/rss.xml"

[[feeds]]
type = "youtube"
title = "Computerphile"
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA"

[[feeds]]
type = "blog"
title = "Tweag"
url = "https://www.tweag.io/rss.xml"
