name: Deploy Planet

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily update

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Devenv
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Devenv
        run: |
          nix-env -iA devenv -f https://github.com/cachix/devenv/tarball/latest

      - name: Cache Stack
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'planet.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build and Generate Site
        run: |
          devenv shell -- cabal run

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
