name: Scheduled update

on:
  schedule:
    - cron: '0 6,18 * * *' # Twice per day (06:00 and 18:00 UTC)
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Devenv
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Devenv CLI
        run: |
          nix profile install --accept-flake-config github:cachix/devenv/latest

      - name: Restore Cabal Store
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/store
            ~/.cabal/packages
          key: ${{ runner.os }}-cabal-${{ hashFiles('planet.cabal', 'devenv.lock') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Restore Dist
        uses: actions/cache@v4
        with:
          path: dist-newstyle
          key: build-dist-restore
          restore-keys: |
            build-dist-

      - name: Generate Site
        run: devenv shell -- make run

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
