name: Scheduled update

on:
  schedule:
    - cron: '0 0,6,12,18 * * *' # Four times per day
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore Planet CLI
        uses: actions/cache/restore@v4
        id: cache-planet-cli
        with:
          path: planet
          key: planet-bin-
          restore-keys: |
            planet-bin-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: elm-app/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('elm-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Cache elm-stuff
        id: cache-elm-stuff
        uses: actions/cache@v4
        with:
          path: elm-app/elm-stuff
          key: ${{ runner.os }}-elm-${{ hashFiles('elm-app/elm.json') }}
          restore-keys: |
            ${{ runner.os }}-elm-

      - name: Generate Data
        run: ./planet

      - name: Build Elm App
        run: |
          cd elm-app
          npm install
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./elm-app/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
